# # To Display Home Page/ Login or logout status
# http://localhost:3000

# # To Get all STUDENT
# http://localhost:3000/STUDENT

# To Get all users
http://localhost:3000/user

# To Get  Single STUDENT
http://localhost:3000/STUDENT/65b3fd387b6b41b033b909cf


# To Get Single User
http://localhost:3000/user/65b4d906e870bbc5cbe79db8

# To open swagger
http://localhost:3000/api-docs

# My Published link that display home page
https://studentrecords2024.onrender.com

studentrecords2024.onrender.com
# My Published link to open swagger
https://studentrecords2024.onrender.com/api-docs

# My Production link that returns all STUDENT
https://studentrecords2024.onrender.com/STUDENT

# My Production link that returns all user
https://studentrecords2024.onrender.com/user

# My Production link that returns STUDENT by Id
https://studentrecords2024.onrender.com/STUDENT

# My Production link that returns user by Id
https://studentrecords2024.onrender.com/user/

# To login
 http://localhost:3000/login
 
# To logout
 http://localhost:3000/logout

#  To login 
https://studentrecords2024.onrender.com/login

#  To login 
https://studentrecords2024.onrender.com/logout