# # To Display Home Page/ Login or logout status
# http://localhost:3000

# # To Get all students
# http://localhost:3000/students

# To Get all users
http://localhost:3000/user

# To Get  Single students
http://localhost:3000/students/65b3fd387b6b41b033b909cf


# To Get Single User
http://localhost:3000/user/65b4d906e870bbc5cbe79db8

# To open swagger
http://localhost:3000/api-docs

# My Published link that display home page
https://studentsrec24.onrender.com


# My Published link to open swagger
https://studentsrec24.onrender.com/api-docs

# My Production link that returns all students
https://studentsrec24.onrender.com/students

# My Production link that returns all user
https://studentsrec24.onrender.com/user

# My Production link that returns students by Id
https://studentsrec24.onrender.com/students/65b3fd387b6b41b033b909cf

# My Production link that returns user by Id
https://studentsrec24.onrender.com/user/65b4d906e870bbc5cbe79db8

# To login
 http://localhost:3000/login
 
# To logout
 http://localhost:3000/logout

#  To login 
https://studentsrec24.onrender.com/login

#  To login 
https://studentsrec24.onrender.com/logout